name: Simulate User Activity
on:
  schedule:
    - cron: '0 8,14,20 * * *'  # 3 times daily at different hours
  workflow_dispatch:

jobs:
  simulate-users:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate realistic user interaction
        run: |
          urls=(
            "https://portfoliolandingpy.streamlit.app/"
            "https://leadintelligencedemopy.streamlit.app/"
            "https://customersuccessragpy.streamlit.app/"
            "https://revenuedashboardpy.streamlit.app/"
          )
          
          for url in "${urls[@]}"; do
            echo "Simulating user visit to $url"
            
            # More realistic user simulation
            curl -f -s -L \
              --max-time 45 \
              --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" \
              --referer "https://google.com" \
              --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
              --header "Accept-Language: en-US,en;q=0.5" \
              --header "Accept-Encoding: gzip, deflate" \
              --header "Connection: keep-alive" \
              --header "Upgrade-Insecure-Requests: 1" \
              "$url" > /dev/null
            
            if [ $? -eq 0 ]; then
              echo "✅ Successfully visited $url"
            else
              echo "❌ Failed to visit $url"
            fi
            
            # Random delay between 20-40 seconds
            sleep $((20 + RANDOM % 21))
          done
